---
title: "VectorByte Training Materials 2026"
format:
  html:
    toc: true
    toc-location: left
    html-math-method: katex
---

<br>

## Pre-work and set-up

### Pre-workshop reading

Before attending the workshop, we request that you read the following three papers, as they will provide much of the conceptual framework that we rely on:

1. [MIReAD, a minimum information standard for reporting arthropod abundance data](https://www.nature.com/articles/s41597-019-0042-5)

2. [MIReVTD, a minimum information standard for reporting vector trait data](https://academic.oup.com/gigascience/article/doi/10.1093/gigascience/giag020/8502135)

3. [The Role of Vector Trait Variation in Vector-Borne Disease Dynamics](https://www.frontiersin.org/journals/ecology-and-evolution/articles/10.3389/fevo.2020.00189/full)

<br>


### Hardware and Software

- We will be using [`R`](https://cran.r-project.org/) for all data manipulation and analyses/model fitting. Any operating system (Windows, Mac, Linux) will do, as long as you have `R` (version 3.6 or higher) installed.

- You may use any IDE/ GUI for `R` (VScode, RStudio, Emacs, etc). For most people, [`RStudio`](https://www.rstudio.com/) is a good option. Whichever one you decide to use, please make sure it is installed and tested before the workshop.

- We also host all materials on [GitHub](https://github.com/), and all students should have a GitHub account. 

<br>


### Optional: Review of `R` and Statistics

We are assuming familiarity with `R` basics as well as at least introductory statistics, including up through simple linear regression. If you would like materials to review, we recommend the following from [The Multilingual Quantitative Biologist](https://mhasoba.github.io/TheMulQuaBio/intro.html).


1. `R`: [Biological Computing in R Chapter](https://mhasoba.github.io/TheMulQuaBio/notebooks/07-R.html). 

2. Basic statistics, through linear models: [The Multilingual Quantitative Biologist - Basic Data Analyses and Statistics](https://mhasoba.github.io/TheMulQuaBio/Stats-Intro.html).



<br> <br>

## Live Workshop Materials

### Introduction to the Workshops

- [Lecture Slides](VB_Welcome.qmd)

<br> 

### Introduction to Git

- [Coming Soon! -- with EEID](https://eeidworkshop2026.github.io/home/materials.html#introduction-to-github-through-r)

<br>


### Introduction to Data Types and Sources

- [Coming Soon! -- with EEID](https://eeidworkshop2026.github.io/home/materials.html)

<br> 

### Introduction to Traits

- [Lecture Slides](VB_intro_to_traits.qmd)

<br> 

### Intro to the VecTraits Database

- [Lecture](VB_intro_to_vectraits.qmd)

<br>

###  The VecTraits AI assisted digitization pipeline

- [Coming Soon!]()

<br>

### Simple TPC fitting pipeline using NLLS

- [Practical](vectorByte2026_NLLS.qmd)
- [Dataset access code](code/VecTraits_Dataset_Access.R)

<br>


### Introduction to the VecDyn database

-  [Intro to VecDyn (slides)](https://docs.google.com/presentation/d/1GZuAR8zFRFJaR1QConiNHG5v71W4psAd/edit?usp=sharing&ouid=103950001421882927979&rtpof=true&sd=true)
-   [The VecDyn website](https://vectorbyte.crc.nd.edu/vecdyn-datasets)
-   [About the VecDyn API](https://www.vectorbyte.org/blog/vecdyn-api)


<br> 

### Environmental covariates for time and space dependent data

- [Guided Introduction](VByteWkshp26_Climate_SJR.qmd)

<br>

### Introduction to Time Dependent Data

- [Coming Soon!]()

<br>

### Simple Time-dependent data pipeline

- [Coming Soon!]()

<br>

